export const animals = [
     {
          "id": "0",
          "letter": "A",
          "type": "alpaca",
          "name": 'Alpaca',
          "audio": 'alpaca',
     },
     {
          "id": "1",
          "letter": "B",
          "type": "bear",
          "name": 'Bear',
          "audio": 'bear',
     },
     {
          "id": "2",
          "letter": "C",
          "type": "cat",
          "name": 'Cat',
          "audio": 'cat',
     },
     {
          "id": "3",
          "letter": "D",
          "type": "donkey",
          "name": 'Donkey',
          "audio": 'donkey',
     },
     {
          "id": "4",
          "letter": "E",
          "type": "elephant",
          "name": 'Elephant',
          "audio": 'elephant',
     },
     {
          "id": "5",
          "letter": "F",
          "type": "frog",
          "name": 'Frog',
          "audio": 'frog',
     },
     {
          "id": "6",
          "letter": "G",
          "type": "giraffe",
          "name": 'Giraffe',
          "audio": 'giraffe',
     },

     {
          "id": "7",
          "letter": "H",
          "type": "hyena",
          "name": 'Hyena',
          "audio": 'hyena',
     },
     {
          "id": "8",
          "letter": "J",
          "type": "jaguar",
          "name": 'Jaguar',
          "audio": 'jaguar',
     },
     {
          "id": "9",
          "letter": "K",
          "type": "koala",
          "name": 'Koala',
          "audio": 'koala',
     },
     {
          "id": "10",
          "letter": "L",
          "type": "lion",
          "name": 'Lion',
          "audio": 'lion',
     },
     {
          "id": "11",
          "letter": "M",
          "type": "monkey",
          "name": 'Monkey',
          "audio": 'monkey',
     },
     {
          "id": "12",
          "letter": "N",
          "type": "nurseShark",
          "name": 'Nurse Shark',
          "audio": 'nurseShark',
     },
     {
          "id": "13",
          "letter": "O",
          "type": "owl",
          "name": 'Owl',
          "audio": 'owl',
     },
     {
          "id": "14",
          "letter": "P",
          "type": "pig",
          "name": 'Pig',
          "audio": 'pig',
     },
     {
          "id": "15",
          "letter": "Q",
          "type": "quail",
          "name": 'Quail',
          "audio": 'quail',
     },
     {
          "id": "16",
          "letter": "R",
          "type": "raccoon",
          "name": 'Raccoon',
          "audio": 'raccoon',
     },
     {
          "id": "17",
          "letter": "S",
          "type": "snake",
          "name": 'Snake',
          "audio": 'snake',
     },
     {
          "id": "18",
          "letter": "T",
          "type": "tiger",
          "name": 'Tiger',
          "audio": 'tiger',
     },
     {
          "id": "19",
          "letter": "U",
          "type": "urial",
          "name": 'Urial Sheep',
          "audio": 'urial',
     },
     {
          "id": "20",
          "letter": "V",
          "type": "vampireBat",
          "name": 'Vampire Bat',
          "audio": 'vampireBat',
     },
     {
          "id": "21",
          "letter": "W",
          "type": "whale",
          "name": 'Whale',
          "audio": 'whale',
     },
     {
          "id": "22",
          "letter": "X",
          "type": "xRay",
          "name": 'X Ray Fish',
          "audio": 'xRay',
     },
     {
          "id": "23",
          "letter": "Y",
          "type": "yak",
          "name": 'Yak',
          "audio": 'yak',
     },
     {
          "id": "24",
          "letter": "Z",
          "type": "zebra",
          "name": 'Zebra',
          "audio": 'zebra',
     },


]

export const colors = [
     "#DEFFB7", '#f8bbd0', "#FFFFB5", "#FFBEAB", "#e6ee9c", "#a7ffeb", "#d1c4e9", "#ffe0b2", "#ACE6FF", "#FFE0AC", "#F8D1FF"
]